### PR TITLE
Reverted Source formatting of constants in FacesBuilder.java since those constants must be instantiated in order.

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@brunobasto which version of the portal do you use for the source formatter? I have been using `7.0.0-m3`. Should I be using some other version? 

Also, when I run the formatter, it does not reorder these constants. Do you know why it does reorder them for you?

\- Kyle

**Comment by stiemannkj1** [comment]
That does solve compilation issues, but it still causes a runtime exception.

**Comment by brunobasto** [comment]
Humm, I'm using master. Maybe it's a bug in the formatter...

Maybe we can just revert it for now if you are getting run time exceptions. But just out of curiosity, what are the errors? I thought just calling it like a static attribute would work

**Comment by stiemannkj1** [comment]
I get the following exception:

```
[WARNING]
java.lang.ExceptionInInitializerError
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.liferay.alloy.tools.builder.faces.FacesBuilder.<clinit>(FacesBuilder.java:252)
	... 6 more
[INFO] ---------------
```

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/brunobasto/alloy-generator/compare/7c91308~0...7c91308) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by brunobasto** [comment]
I see. Let's just revert it then.

Thx

**Comment by stiemannkj1** [comment]
Okay thank you, I will look into fixing the formatter settings to work with master or changing the way I use the constants to make it work with the formatted order.

**Comment by brunobasto** [comment]
Ok, I'd say we should fix the formatter. It shouldn't break our code.

**Pull request merged**
